addons:
  sonarcloud:
    organization: saschaiseli_otc_trainingservice
language: java
jdk:
 - oraclejdk8
install:
- mvn clean test
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -DskipIntegrationTests=true