addons:
  sonarcloud:
    organization: saschaiseli_otc_trainingservice
language: java
jdk:
 - oraclejdk8
before_install:
- mvn clean
install:
- mvn install
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -DskipIntegrationTests=true