sudo: required
addons:
  sonarcloud:
    organization: saschaiseli-github
    projectKey: saschaiseli_otc_trainingservice
language: java
jdk:
 - oraclejdk8
before_install:
- mvn clean
install:
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar coveralls:report install -DskipIntegrationTests=true