sudo: required
addons:
  sonarcloud:
    organization: saschaiseli-github
    projectKey: saschaiseli_otc_trainingservice
language: java
jdk:
  - oraclejdk8
before_install:
  - sudo service mysql stop
  - mvn clean
install:
  - mvn install
script:
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent coveralls:report -Pintegration