addons:
  sonarcloud:
    organization: saschaiseli-github
    projectKey: saschaiseli_otc_trainingservice
language: java
jdk:
 - oraclejdk8
before_install:
- mvn clean
install:
- mvn install -DskipIntegrationTests=true
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar coveralls:report -DskipIntegrationTests=true