language: java
jdk:
 - oraclejdk8
install:
- mvn install -DskipTests=true -Dspring.profiles.active=test -Dmaven.javadoc.skip=true -B -V
script:
- mvn test -Dspring.profiles.active=test 
after_success:
- mvn clean test jacoco:report coveralls:report