version: '3'
services:
  postgres:
    image: postgres:11.3-alpine
    restart: always
    ports:
      - 54320:${DB_PORT_COMPOSE}
    environment:
      - POSTGRES_USER=${DB_USER_COMPOSE}
      - POSTGRES_PASSWORD=${DB_PASS_COMPOSE}
      - POSTGRES_DB=${DB_DATABASE_COMPOSE}
    volumes:
      - ${DB_HOST_VOLUME}:/var/lib/postgresql/data
  trainingservice:
    image: iselisa/trainingservice:${SERVICE_VERSION}
    ports:
      - ${APP_PORT}:8080
      - ${APP_ADMIN_PORT}:9990
      - ${APP_DEBUG_PORT}:8787
    environment:
      - DB_USERNAME=${DB_USER_COMPOSE}
      - DB_PASSWORD=${DB_PASS_COMPOSE}
      - DB_HOST=${DB_HOST_COMPOSE}
      - DB_PORT=${DB_PORT_COMPOSE}
      - DB_DATABASE=${DB_DATABASE_COMPOSE}
      - isDev=true
    depends_on:
      - postgres