version: '3'
services:
  mariadb:
    image: bitnami/mariadb:latest
    labels:
      kompose.service.type: nodeport
    networks:
      - backend
    ports:
      - ${DB_PORT_COMPOSE}:3306
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${DB_USER_COMPOSE}
      - MARIADB_PASSWORD=${DB_PASS_COMPOSE}
      - MARIADB_DATABASE=${DB_DATABASE_COMPOSE}
  trainingservice:
    image: iselisa/trainingservice:latest
    ports:
      - 8282:8080
      - 9999:9990
    external_links:
      - mariadb
    networks:
      - backend
    environment:
      - DB_USERNAME=${DB_USER_COMPOSE}
      - DB_PASSWORD=${DB_PASS_COMPOSE}
      - DB_HOST=mariadb
      - DB_PORT=${DB_PORT_COMPOSE}
      - DB_DATABASE=${DB_DATABASE_COMPOSE}
      - isDev=true
networks:
  backend:
    driver: bridge
